apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overleaf
  namespace: argocd
spec:
  project: homelab
  
  source:
    # 1. The NEW repository URL from the deprecation notice
    repoURL: 'https://bjw-s.github.io/helm-charts/'
    # 2. The NEW chart name
    chart: 'app-template'
    # 3. A recent version of the new chart
    targetRevision: '3.3.1' 
    
    helm:
      values: |
        image:
          repository: sharelatex/sharelatex
          tag: latest # You can pin this to a specific version

        service:
          main:
            ports:
              http:
                port: 80 # Overleaf serves on port 80

        ingress:
          main:
            enabled: true
            hosts:
              - host: "overleaf.pasuko.com"
                paths:
                  - path: /
                    pathType: ImplementationSpecific

        persistence:
          data:
            enabled: true
            storageClass: "local-path"
            accessMode: "ReadWriteOnce"
            size: "10Gi"
            # This is the correct data path inside the Overleaf container
            mountPath: /var/lib/sharelatex 

        env:
          SHARELATEX_MONGO_URL: "mongodb://mongodb-master.overleaf.svc.cluster.local:27017/sharelatex"
          SHARELATEX_REDIS_URL: "redis://redis-master.overleaf.svc.cluster.local:6379"
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'overleaf'
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true