apiVersion: v1
kind: Namespace
metadata:
  name: superset
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-env
  namespace: superset
data:
  # Persisted home under our PVC
  SUPERSET_HOME: "/app/superset_home"
  # SQLite DB file on the mounted volume (four slashes after sqlite:)
  SQLALCHEMY_DATABASE_URI: "sqlite:////app/superset_home/superset.db"
  SUPERSET_LOAD_EXAMPLES: "no"
  SUPERSET_WEBSERVER_TIMEOUT: "60"
---
# Storage for the SQLite file & Superset home
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-home
  namespace: superset
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
# Internal Service
apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: superset
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8088
      targetPort: 8088
  selector:
    app: superset
---
# Superset (single replica; no Celery/Redis/Postgres)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: superset
spec:
  replicas: 1   # IMPORTANT: keep 1 with SQLite
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      securityContext:
        fsGroup: 65534        # ensure volume is writable (nobody)
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: superset-home
          persistentVolumeClaim:
            claimName: superset-home
      initContainers:
        - name: init-db
          image: apache/superset:5.0.0
          envFrom:
            - configMapRef: { name: superset-env }
            - secretRef:   { name: superset-secrets }
          volumeMounts:
            - name: superset-home
              mountPath: /app/superset_home
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eu
              # Initialize/upgrade metadata DB (creates SQLite file if missing)
              superset db upgrade
              # Create admin (idempotent) and perform base init
              superset fab create-admin \
                --username "${SUPERSET_ADMIN_USERNAME}" \
                --firstname "${SUPERSET_ADMIN_FIRSTNAME}" \
                --lastname "${SUPERSET_ADMIN_LASTNAME}" \
                --email "${SUPERSET_ADMIN_EMAIL}" \
                --password "${SUPERSET_ADMIN_PASSWORD}" || true
              superset init
      containers:
        - name: web
          image: apache/superset:5.0.0
          envFrom:
            - configMapRef: { name: superset-env }
            - secretRef:   { name: superset-secrets }
          volumeMounts:
            - name: superset-home
              mountPath: /app/superset_home
          ports:
            - containerPort: 8088
          readinessProbe:
            httpGet: { path: /health, port: 8088 }
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8088 }
            initialDelaySeconds: 45
            periodSeconds: 20
          # No DB drivers needed for SQLite; keep entrypoint simple
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eu
              exec gunicorn --bind 0.0.0.0:8088 --workers 3 --timeout 120 "superset.app:create_app()"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1500m"
              memory: "2Gi"
---
# Ingress (Traefik example — adjust host/annotations to your setup)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: superset
  namespace: superset
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: superset.pasuko.com   # <-- change if needed
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: superset
                port:
                  name: http
