apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcpgateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bencejdanko/manifests.git
    targetRevision: main
    path: apps/mcp
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
