apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langflow-data
  namespace: langflow
spec:
  storageClassName: local-path
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
