apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bencejdanko/manifests.git   # <-- change me
    targetRevision: main
    path: apps/superset
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: superset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Validate=true
